{
 "title": "Lämpötila",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Vesivaraajien lämpötilat",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Alavaraaja",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "savia",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "sauna/varaaja/ala" }
     ]
    },
    {
     "alias": "Tasku",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "savia",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "sauna/varaaja/tasku" }
     ]
    },
    {
     "alias": "Ylävaraaja",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "savia",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "sauna/varaaja/yla" }
     ]
    }
   ]
  },
  {
   "title": "Vantaa",
   "type": "graph",
   "description": "Sensori sijaitsee parvekkeella",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "sensorpi",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1.6 - 7" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "outside/temperature" }
     ]
    }
   ]
  },
  {
   "title": "Reference",
   "type": "graph",
   "description": "Temperature provided by OpenWeatherMap. This data is used to correct sensor inaccuracy of SenseHat due to Raspberry Pi CPU proximity.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "openweather",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "vantaa/realtemp" }
     ]
    }
   ]
  },
  {
   "title": "Lämpötila tunnin välein",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "sensorpi",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1.6-7" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "outside/temperature" }
     ]
    }
   ]
  },
  {
   "title": "Lämpötila tunnin välein (FROM REF)",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "openweather",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "vantaa/realtemp" }
     ]
    }
   ]
  }
 ]
}